' Developer Express Code Central Example:
' How to fix a row in GridControl
' 
' This example demonstrates how to provide the capability to fix a row in
' GridControl. Our GridControl doesn't have the capability to fix a row. So, to
' provide this capability in this sample, we manipulate
' the child collection of
' the HeirarchyPanel. We add a StackPanel with a collection of editors to the
' child
' collection of the HeirarchyPanel and bind them to respective cells of the
' selected row. Then, we assign
' it to a ScrollChanged event of the ScrollViewer.
' When ScrollChanged raises, we change the location of the StackPanel, so it is
' always displayed on the top of the grid view.
' Please note, that this approach
' is not compatible with Bands and Conditional Formatting. Also, a fixed row may
' not be displayed immediately when PerPixelScrolling is enabled.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T161325

' Developer Express Code Central Example:
' How to fix a row in GridControl
' 
' This example demonstrates how to provide the capability to fix a row in
' GridControl. Our GridControl doesn't have the capability to fix a row. So, to
' provide this capability in this sample, we manipulate
' the child collection of
' the HeirarchyPanel. We add a StackPanel with a collection of editors to the
' child
' collection of the HeirarchyPanel and bind them to respective cells of the
' selected row. Then, we assign
' it to a ScrollChanged event of the ScrollViewer.
' When ScrollChanged raises, we change the location of the StackPanel, so it is
' always displayed on the top of the grid view.
' Please note, that this approach
' is not compatible with Bands and Conditional Formatting. Also, a fixed row may
' not be displayed immediately when PerPixelScrolling is enabled.
' 
' You can find sample updates and versions for different programming languages here:
' http://www.devexpress.com/example=T161325

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Namespace My.Resources


	''' <summary>
	'''   A strongly-typed resource class, for looking up localized strings, etc.
	''' </summary>
	' This class was auto-generated by the StronglyTypedResourceBuilder
	' class via a tool like ResGen or Visual Studio.
	' To add or remove a member, edit your .ResX file then rerun ResGen
	' with the /str option, or rebuild your VS project.
	<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
	Global.Microsoft.VisualBasic.HideModuleNameAttribute()>
	Friend Module Resources

		Private resourceMan As Global.System.Resources.ResourceManager

		Private resourceCulture As Global.System.Globalization.CultureInfo

'		internal Resources()
'		{
'		}

		''' <summary>
		'''   Returns the cached ResourceManager instance used by this class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
			Get
				If (resourceMan Is Nothing) Then
					Dim temp As New Global.System.Resources.ResourceManager("Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		''' <summary>
		'''   Overrides the current thread's CurrentUICulture property for all
		'''   resource lookups using this strongly typed resource class.
		''' </summary>
		<Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>
		Friend Property Culture() As Global.System.Globalization.CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(ByVal value As System.Globalization.CultureInfo)
				resourceCulture = value
			End Set
		End Property
	End Module
End Namespace
